services:
  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=test
    ports:
      - 33061:3306
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./../../:/home/devops
